PaySys/urls.py
from django.shortcuts import redirect
from django.urls import path

from PaySys.views import *

app_name = "paysys"

urlpatterns = [
    path('buy/', api_get_buyItem, name='buyItemId'),
    path('item/<int:id>/', viewItem, name='viewItemId'),
    path('catalog/', viewCatalog, name='viewCatalog'),
    path('cart/', viewCart, name='viewCart'),
    path('config/', stripe_config),
    path('webhook/', stripe_webhook),
    path('success/', success_stripe),
    path('cancelled/', cancelled_stripe),
    path('', lambda request: redirect('catalog/', permanent=True))
]

Rishat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Rishat import settings

urlpatterns = [
    path('', include('PaySys.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block metas %}{% endblock %}
    <title>{% block title %}Payment system{% endblock %}</title>
    {% block styles %}{% endblock %}
    {% block scripts %}{% endblock %}

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-brand">Магазин</div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'paysys:viewCatalog' %}">Каталог</a>
                <a class="nav-link " href="{% url 'paysys:viewCart' %}">Корзина</a>
            </div>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>